# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -Dmaven.test.skip=true --file pom.xml

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop

      - name: Set up MariaDB
        uses: getong/mariadb-action@v1.1
        with:
          mysql database: 'java'
          mysql root password: ${{secrets.databaseRootPassword}}
          mysql user: 'admin'
          mysql password: ${{secrets.databasePassword}}

      - name: Replace ip address in applications config
        run: sed -i 's/192.168.2.55/127.0.0.1/g' ./src/main/java/resources/application.properties