# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

#    - name: replace db credentials in pom.xml
#      run: |
#        sed -i 's/\%DB_USER%/${{secrets.DB_USER}}/g' pom.xml && sed -i 's/\%DB_PASSWORD\%/${{secrets.databasePassword}}/g' pom.xml && sed -i 's/%NEXUS_URL%/${{secrets.NEXUS_URL}}/g' pom.xml && \
#        sed -i 's/192.168.2.55/127.17.0.1/g' ./src/main/resources/application.properties && \
#        sed -i 's/%DB_USER%/${{secrets.DB_USER}}/g' src/main/resources/application.properties && sed -i 's/%DB_PASSWORD%/${{secrets.databasePassword}}/g' src/main/resources/application.properties

    - run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set up MariaDB
        uses: getong/mariadb-action@v1.1
        with:
          mysql database: 'java'
          mysql user: ${{secrets.DB_USER}}
          mysql password: ${{secrets.databasePassword}}

      - name: replace server ip
        run: sed -i 's/192.168.2.55/127.17.0.1/g' ./src/main/resources/application.properties
#      - name: replace db credentials in pom.xml
#        run: |
#            sed -i 's/%DB_USER%/${{secrets.DB_USER}}/g' pom.xml && sed -i 's/%DB_PASSWORD%/${{secrets.DATABASEPASSWORD}}/g' pom.xml && sed -i 's/%NEXUS_URL%/${{secrets.NEXUS_URL}}/g' pom.xml && \
#            sed -i 's/192.168.2.55/127.17.0.1/g' ./src/main/resources/application.properties && \
#            sed -i 's/%DB_USER%/${{secrets.DB_USER}}/g' src/main/resources/application.properties && sed -i 's/%DB_PASSWORD%/${{secrets.databasePassword}}/g' src/main/resources/application.properties

      - name: Test application
        run: mvn -B verify --file pom.xml

  deploy:
      runs-on: ubuntu-latest
      needs:
        - test
        - build
      steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven
#        - name: replace db credentials in pom.xml
#          run: |
#            sed -i 's/%DB_USER%/${{secrets.DB_USER}}/g' pom.xml && sed -i 's/%DB_PASSWORD%/${{secrets.DATABASEPASSWORD}}/g' pom.xml && sed -i 's/%NEXUS_URL%/${{secrets.NEXUS_URL}}/g' pom.xml && \
#            sed -i 's/192.168.2.55/127.17.0.1/g' ./src/main/resources/application.properties && \
#            sed -i 's/%DB_USER%/${{secrets.DB_USER}}/g' src/main/resources/application.properties && sed -i 's/%DB_PASSWORD%/${{secrets.databasePassword}}/g' src/main/resources/application.properties

        - name: deploy to nexus
          run: mvn clean deploy -Dmaven.test.skip=true

        - name: increment version number
          run: mvn validate -DbumpPatch

        - name: Commit new version
          run: |
            git config --global user.name 'Gabor Horvath'
            git config --global user.email 'gaborka812@gmail.com'
            git commit -am "Increment pom version"
            git push

